development:
  bucket_name: picaday_development
  access_key_id:    
  secret_access_key: 
 
test:
  bucket_name: picaday_test
  access_key_id:    
  secret_access_key: 
   
production:
  bucket_name: picaday
  access_key_id:    
  secret_access_key: 